pipeline {
    agent any
    tools {
        maven 'M3'   // matches the Maven installation name in Jenkins
    }
    stages {
        stage('Checkout Git') {
            steps {
                git branch: 'main', url: 'https://github.com/srikrishnaedu18-git/Repo-18-12-25.git'
            }
        }
        stage('Build and Test') {
            steps {
                sh 'mvn clean test'
            }
        }
    }
}
