pipeline {
    agent any
    tools {
        maven 'M3'
    }
    stages {
        stage('Checkout Git') {
            steps {
                git branch: 'main', url: 'https://github.com/srikrishnaedu18-git/Repo-18-12-25.git'
            }
        }
        stage('Build and Test') {
            steps {
                dir('simple-maven-app') { 
                    sh 'mvn clean test'
                }
            }
        }
    }
}
